DATABASE:
  SNOWFLAKE_ACCOUNT: "si44367.eu-central-1"
  SNOWFLAKE_WAREHOUSE: 'DS_DEV_WH'
  SNOWFLAKE_DATABASE: 'DS_DEV'
  SNOWFLAKE_SCHEMA: 'SCHEMA_NAME'
  SNOWFLAKE_ROLE: "DS_DEV_TEAM_ROLE"

S3:
  BUCKET_NAME: "415280201047-dazn-domino-USER-sandbox"
    
