version: 1
formatters:
  long:   
    format: '%(asctime)s|%(levelname)s|%(name)s|%(filename)s|%(funcName)s|%(message)s' 
  brief: 
    format: '%(levelname)s|%(name)s|%(filename)s|%(funcName)s|%(message)s' 
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: brief
    stream: ext://sys.stdout
  S3:
    class: logging.StreamHandler
    level: INFO
    formatter: long  
root:
  level: INFO
  handlers: [console,S3]